#!/usr/bin/env bun
/**
 * Database Schema Push Script
 * Synchronizes schema definitions to SQLite database
 * For development use - creates/updates tables directly from schema
 */

import { drizzle } from 'drizzle-orm/bun-sqlite';
import Database from 'bun:sqlite';
import * as schema from '../src/db/schema';
import { sql } from 'drizzle-orm';
import { existsSync, mkdirSync } from 'fs';
import { resolve } from 'path';

const DATABASE_PATH = process.env.DATABASE_PATH || './data/nodehub.db';

console.log('🔄 Pushing schema to database...');
console.log(`📂 Database: ${DATABASE_PATH}`);

// Ensure data directory exists
const dbDir = resolve(DATABASE_PATH, '..');
if (!existsSync(dbDir)) {
  mkdirSync(dbDir, { recursive: true });
}

// Create database connection
const sqlite = new Database(DATABASE_PATH);

// Enable foreign keys
sqlite.exec('PRAGMA foreign_keys = ON');

// Create Drizzle instance
const db = drizzle(sqlite, { schema });

// Get all table names from schema
const tables = Object.keys(schema).filter(
  (key) => key !== 'dnsRecords' && typeof schema[key as keyof typeof schema] === 'object'
);

console.log(`📋 Found ${tables.length} tables in schema`);

try {
  // Check existing tables
  const existingTables = sqlite.prepare(
    "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
  ).all() as { name: string }[];

  const existingTableNames = new Set(existingTables.map(t => t.name));

  console.log(`📊 Existing tables: ${existingTableNames.size}`);

  // For SQLite with Drizzle, we need to use the SQL generated by Drizzle
  // This is a simplified version - for production, use migrations
  console.log('');
  console.log('⚠️  For production, use migrations instead:');
  console.log('     1. Run: bun run db:generate');
  console.log('     2. Run: bun run db:migrate');
  console.log('');
  console.log('ℹ️  For development, the database will be auto-created on first run');

  sqlite.close();
  console.log('✅ Database ready');
} catch (error) {
  console.error('❌ Error:', error);
  sqlite.close();
  process.exit(1);
}
